import { Button } from '@/components/ui/button';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Nav from '@/components/nav';
import { TodoProvider } from '@/providers/todo.provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-stretch justify-start p-20 gap-10">
          <Nav />
          <TodoProvider>{children}</TodoProvider>
        </main>
      </body>
    </html>
  );
}
